/* Public-domain / original exercise tunes only. No commercial karaoke tracks. */
window.VOICE_SONGS = [
  {
    id: "scale",
    title: "Hum the scale",
    credit: "Original warm-up · public-domain exercise",
    bpm: 80,
    notes: [
      { midi: 60, beats: 2, lyric: "Do" },
      { midi: 62, beats: 2, lyric: "Re" },
      { midi: 64, beats: 2, lyric: "Mi" },
      { midi: 65, beats: 2, lyric: "Fa" },
      { midi: 67, beats: 2, lyric: "Sol" },
      { midi: 69, beats: 2, lyric: "La" },
      { midi: 71, beats: 2, lyric: "Ti" },
      { midi: 72, beats: 3, lyric: "Do" },
      { midi: 71, beats: 2, lyric: "Ti" },
      { midi: 69, beats: 2, lyric: "La" },
      { midi: 67, beats: 2, lyric: "Sol" },
      { midi: 65, beats: 2, lyric: "Fa" },
      { midi: 64, beats: 2, lyric: "Mi" },
      { midi: 62, beats: 2, lyric: "Re" },
      { midi: 60, beats: 4, lyric: "Do" }
    ]
  },
  {
    id: "grace",
    title: "Amazing Grace",
    credit: "Public domain · John Newton, 1779",
    bpm: 72,
    notes: [
      { midi: 62, beats: 1, lyric: "A-" },
      { midi: 67, beats: 2, lyric: "maz" },
      { midi: 71, beats: 0.5, lyric: "ing" },
      { midi: 67, beats: 0.5, lyric: "grace," },
      { midi: 71, beats: 2, lyric: "how" },
      { midi: 69, beats: 2, lyric: "sweet" },
      { midi: 67, beats: 1.5, lyric: "the" },
      { midi: 64, beats: 0.5, lyric: "sound" },
      { midi: 62, beats: 3, lyric: "" },
      { midi: 62, beats: 1, lyric: "that" },
      { midi: 67, beats: 2, lyric: "saved" },
      { midi: 71, beats: 0.5, lyric: "a" },
      { midi: 67, beats: 0.5, lyric: "wretch" },
      { midi: 71, beats: 2, lyric: "like" },
      { midi: 69, beats: 2, lyric: "me." },
      { midi: 74, beats: 4, lyric: "" },
      { midi: 74, beats: 1, lyric: "I" },
      { midi: 74, beats: 1.5, lyric: "once" },
      { midi: 71, beats: 0.5, lyric: "was" },
      { midi: 67, beats: 1, lyric: "lost," },
      { midi: 71, beats: 2, lyric: "but" },
      { midi: 69, beats: 2, lyric: "now" },
      { midi: 67, beats: 1.5, lyric: "am" },
      { midi: 64, beats: 0.5, lyric: "found;" },
      { midi: 62, beats: 3, lyric: "" },
      { midi: 62, beats: 1, lyric: "was" },
      { midi: 67, beats: 2, lyric: "blind," },
      { midi: 71, beats: 0.5, lyric: "but" },
      { midi: 67, beats: 0.5, lyric: "now" },
      { midi: 71, beats: 2, lyric: "I" },
      { midi: 69, beats: 2, lyric: "see." },
      { midi: 67, beats: 4, lyric: "" }
    ]
  },
  {
    id: "gifts",
    title: "Simple Gifts",
    credit: "Public domain · Joseph Brackett, 1848",
    bpm: 96,
    notes: [
      { midi: 67, beats: 1, lyric: "'Tis" },
      { midi: 67, beats: 1, lyric: "the" },
      { midi: 67, beats: 1, lyric: "gift" },
      { midi: 69, beats: 1, lyric: "to" },
      { midi: 71, beats: 1, lyric: "be" },
      { midi: 67, beats: 1, lyric: "sim" },
      { midi: 64, beats: 1, lyric: "ple," },
      { midi: 62, beats: 2, lyric: "" },
      { midi: 64, beats: 1, lyric: "'tis" },
      { midi: 67, beats: 1, lyric: "the" },
      { midi: 67, beats: 1, lyric: "gift" },
      { midi: 69, beats: 1, lyric: "to" },
      { midi: 71, beats: 1, lyric: "be" },
      { midi: 72, beats: 1, lyric: "free," },
      { midi: 71, beats: 1, lyric: "" },
      { midi: 69, beats: 2, lyric: "" },
      { midi: 67, beats: 1, lyric: "'tis" },
      { midi: 67, beats: 1, lyric: "the" },
      { midi: 67, beats: 1, lyric: "gift" },
      { midi: 69, beats: 1, lyric: "to" },
      { midi: 71, beats: 2, lyric: "come" },
      { midi: 69, beats: 1, lyric: "down" },
      { midi: 67, beats: 1, lyric: "where" },
      { midi: 64, beats: 2, lyric: "we" },
      { midi: 62, beats: 1, lyric: "ought" },
      { midi: 60, beats: 3, lyric: "to" },
      { midi: 62, beats: 1, lyric: "be." },
      { midi: 67, beats: 4, lyric: "" }
    ]
  },
  {
    id: "saints",
    title: "When the Saints",
    credit: "Public domain · traditional spiritual",
    bpm: 108,
    notes: [
      { midi: 60, beats: 1, lyric: "Oh" },
      { midi: 64, beats: 1, lyric: "when" },
      { midi: 65, beats: 1, lyric: "the" },
      { midi: 67, beats: 3, lyric: "saints" },
      { midi: 60, beats: 1, lyric: "go" },
      { midi: 64, beats: 1, lyric: "march" },
      { midi: 65, beats: 1, lyric: "ing" },
      { midi: 67, beats: 3, lyric: "in," },
      { midi: 60, beats: 1, lyric: "oh" },
      { midi: 64, beats: 1, lyric: "when" },
      { midi: 65, beats: 1, lyric: "the" },
      { midi: 67, beats: 2, lyric: "saints" },
      { midi: 64, beats: 2, lyric: "go" },
      { midi: 60, beats: 2, lyric: "march" },
      { midi: 64, beats: 1, lyric: "ing" },
      { midi: 62, beats: 3, lyric: "in." },
      { midi: 64, beats: 1, lyric: "Lord," },
      { midi: 64, beats: 1, lyric: "I" },
      { midi: 62, beats: 1, lyric: "want" },
      { midi: 60, beats: 2, lyric: "to" },
      { midi: 60, beats: 1, lyric: "be" },
      { midi: 64, beats: 2, lyric: "in" },
      { midi: 67, beats: 1, lyric: "that" },
      { midi: 67, beats: 1, lyric: "num" },
      { midi: 65, beats: 3, lyric: "ber," },
      { midi: 64, beats: 1, lyric: "when" },
      { midi: 65, beats: 1, lyric: "the" },
      { midi: 67, beats: 2, lyric: "saints" },
      { midi: 64, beats: 2, lyric: "go" },
      { midi: 60, beats: 2, lyric: "march" },
      { midi: 62, beats: 1, lyric: "ing" },
      { midi: 60, beats: 4, lyric: "in." }
    ]
  },
  {
    id: "bonnie",
    title: "My Bonnie",
    credit: "Public domain · traditional",
    bpm: 92,
    notes: [
      { midi: 67, beats: 1, lyric: "My" },
      { midi: 64, beats: 1, lyric: "Bon" },
      { midi: 60, beats: 2, lyric: "nie" },
      { midi: 62, beats: 1, lyric: "lies" },
      { midi: 64, beats: 1, lyric: "o" },
      { midi: 65, beats: 1, lyric: "ver" },
      { midi: 67, beats: 2, lyric: "the" },
      { midi: 67, beats: 2, lyric: "o" },
      { midi: 67, beats: 1, lyric: "cean," },
      { midi: 67, beats: 1, lyric: "my" },
      { midi: 62, beats: 1, lyric: "Bon" },
      { midi: 62, beats: 2, lyric: "nie" },
      { midi: 64, beats: 1, lyric: "lies" },
      { midi: 62, beats: 1, lyric: "o" },
      { midi: 60, beats: 4, lyric: "ver" },
      { midi: 62, beats: 1, lyric: "the" },
      { midi: 60, beats: 3, lyric: "sea." },
      { midi: 67, beats: 1, lyric: "My" },
      { midi: 64, beats: 1, lyric: "Bon" },
      { midi: 60, beats: 2, lyric: "nie" },
      { midi: 62, beats: 1, lyric: "lies" },
      { midi: 64, beats: 1, lyric: "o" },
      { midi: 65, beats: 1, lyric: "ver" },
      { midi: 67, beats: 2, lyric: "the" },
      { midi: 67, beats: 2, lyric: "o" },
      { midi: 67, beats: 1, lyric: "cean." },
      { midi: 69, beats: 1, lyric: "Oh" },
      { midi: 69, beats: 1, lyric: "bring" },
      { midi: 67, beats: 1, lyric: "back" },
      { midi: 65, beats: 1, lyric: "my" },
      { midi: 64, beats: 2, lyric: "Bon" },
      { midi: 62, beats: 1, lyric: "nie" },
      { midi: 60, beats: 4, lyric: "to me." }
    ]
  },
  {
    id: "twinkle",
    title: "Twinkle, Twinkle",
    credit: "Public domain · traditional French melody",
    bpm: 100,
    notes: [
      { midi: 60, beats: 1, lyric: "Twin" },
      { midi: 60, beats: 1, lyric: "kle," },
      { midi: 67, beats: 1, lyric: "twin" },
      { midi: 67, beats: 1, lyric: "kle," },
      { midi: 69, beats: 1, lyric: "lit" },
      { midi: 69, beats: 1, lyric: "tle" },
      { midi: 67, beats: 2, lyric: "star," },
      { midi: 65, beats: 1, lyric: "how" },
      { midi: 65, beats: 1, lyric: "I" },
      { midi: 64, beats: 1, lyric: "won" },
      { midi: 64, beats: 1, lyric: "der" },
      { midi: 62, beats: 1, lyric: "what" },
      { midi: 62, beats: 1, lyric: "you" },
      { midi: 60, beats: 2, lyric: "are." },
      { midi: 67, beats: 1, lyric: "Up" },
      { midi: 67, beats: 1, lyric: "a" },
      { midi: 65, beats: 1, lyric: "bove" },
      { midi: 65, beats: 1, lyric: "the" },
      { midi: 64, beats: 1, lyric: "world" },
      { midi: 64, beats: 1, lyric: "so" },
      { midi: 62, beats: 2, lyric: "high," },
      { midi: 67, beats: 1, lyric: "like" },
      { midi: 67, beats: 1, lyric: "a" },
      { midi: 65, beats: 1, lyric: "dia" },
      { midi: 65, beats: 1, lyric: "mond" },
      { midi: 64, beats: 1, lyric: "in" },
      { midi: 64, beats: 1, lyric: "the" },
      { midi: 62, beats: 2, lyric: "sky." },
      { midi: 60, beats: 1, lyric: "Twin" },
      { midi: 60, beats: 1, lyric: "kle," },
      { midi: 67, beats: 1, lyric: "twin" },
      { midi: 67, beats: 1, lyric: "kle," },
      { midi: 69, beats: 1, lyric: "lit" },
      { midi: 69, beats: 1, lyric: "tle" },
      { midi: 67, beats: 2, lyric: "star," },
      { midi: 65, beats: 1, lyric: "how" },
      { midi: 65, beats: 1, lyric: "I" },
      { midi: 64, beats: 1, lyric: "won" },
      { midi: 64, beats: 1, lyric: "der" },
      { midi: 62, beats: 1, lyric: "what" },
      { midi: 62, beats: 1, lyric: "you" },
      { midi: 60, beats: 3, lyric: "are." }
    ]
  }
];
